### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by RainbowDashLabs** [RainbowDashLabs/reputation-bot#118]
Create a FAQ and explain some things

- [x] Emoji Debugging
- [x] Why cant I give reputation to user XY
- [x] What is a context
- [x] What roles will be given and removed by the bot
- [x] How can I remove reputation of a user
- [x] A user has left the guild but still shows up in top command
- [x] How can I request my data
- [x] How can I delete my data

**Comment by Taucher2003** [comment]
All points are checked.
Is this done and can be closed?

**Comment by RainbowDashLabs** [comment]
Probably yes
