### ISSUE TITLE
[bug?] few usernames on leaderboard aren't shown as usernames, it displays numbers instead

### ISSUE THREAD

**Issue by micalevisk** [RainbowDashLabs/reputation-bot#171]
at https://discord.gg/nestjs we got the following report from `/top`:

![image](https://user-images.githubusercontent.com/13461315/146650335-bcc31450-6e8f-410b-a9b1-8eb6c416c2fa.png)

**Comment by Taucher2003** [comment]
These are mentions of users your client can't resolve anymore. That is mostly caused by users which have left the guild.

These are periodically purged from the database, so they don't directly loose all of their reputation if they decide to rejoin your guild.

**Comment by micalevisk** [comment]
got it. Thank you!

looks like it managed to find them out. I'm pretty sure that user on **#7** didn't left the guild tho

![image](https://user-images.githubusercontent.com/13461315/146651084-e235844c-1e00-414c-97ba-f579dbe65ef3.png)

**Comment by micalevisk** [comment]
oh, yeah. If I had search for the user on `#10` on server's config, and now the leaderboard shows him.

**Comment by RainbowDashLabs** [comment]
Actually users which are scheduled for deletion are hidden in the leader board already.
If a user is displayed as ids it means that this user is not present in the cache of your client.
Only users which are online, in the first chunk of the channel users or had recent contact with your client via messages are normally cached by the client.

**Comment by micalevisk** [comment]
makes sense.

btw how many users the cache can hold?

**Comment by RainbowDashLabs** [comment]
I don't think this is a fixed amount. It may depend on the available memory on the system and some other factors.
