### ISSUE TITLE
Display order of the names

### ISSUE THREAD

**Issue by Goldmensch** [RainbowDashLabs/reputation-bot#22]
When the bot asks who you want to give reputation to, the names are displayed in a very strange order for mobile. 

current order:
1️⃣ 2️⃣ 
3️⃣ 4️⃣ 
5️⃣ 6️⃣ 

better order:
1️⃣ 4️⃣ 
2️⃣ 5️⃣ 
3️⃣ 6️⃣ 

So it would also be in the right order on mobile:
current order: 
1️⃣ 
3️⃣ 
5️⃣ 
2️⃣ 
4️⃣ 
6️⃣ 

better order:
1️⃣ 
2️⃣ 
3️⃣ 
4️⃣ 
5️⃣ 
6️⃣

**Comment by Skyslycer** [comment]
Made PR: 
[https://github.com/RainbowDashLabs/reputation-bot/pull/23](https://github.com/RainbowDashLabs/reputation-bot/pull/23)
Should fix the issue, but check that.
