### ISSUE TITLE
Numbers into user name?

### ISSUE THREAD

**Issue by iliakan** [RainbowDashLabs/reputation-bot#233]
Hi,

Why some users are numbers after scanning? It just doesn't look nice ;(

How can I replace numbers with usernames?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/349336/161682934-9f69da25-dcfc-4553-82b9-1e39097be9e6.png">

**Comment by RainbowDashLabs** [comment]
The bot uses mentions and writes <@userid>.
These mentions are resolved by the client itself and not by the bot. If you see numbers these users are currently not cached by your client.
To avoid this we would need to make a request for every single user to the discord api, if we dont have it in our cache, which we want to avoid.
Normally users with a high reputation have a high activity on the server as well and will be most likely cached by the client anyway.

**Comment by iliakan** [comment]
I'm using Discord Desktop App. Not API.

Maybe these users are from too old messages?

**Comment by RainbowDashLabs** [comment]
Thats what I said yes ^^

> To avoid this we would need to make a request for every single user to the discord api, if we dont have it in our cache, which we want to avoid.

with "we" I meant the bot. You client does not fetch users on mentions. It only checks the client cache. This cache contains users with recent messages of the current and recent channels. It also includes users currently listed on the user list.

This issue occurs on large servers where offline users are not fetched anymore for the user list. In this case the client is not aware of the users matching on this id.
