### ISSUE TITLE
Strip messages

### ISSUE THREAD

**Issue by RainbowDashLabs** [RainbowDashLabs/reputation-bot#27]
The `MessageAnalyzer` should strip trailing punctuation characters. This is required to make thankword work even when suffixed with such a mark.

When matching the thankword regex a regex like `\y<thankword>\y` is build to enforce word boundaries.
These word boundaries are getting violated by punctuation marks like in the following example.

Following examples arent working, but should work:
`<thankword>!`
`<thankword>.`
`<thankword>, ...`

Think which characters which may proceed these words. Characters like question marks should and could invalidate a thank word.

**Comment by danger-ahead** [comment]
Hi, I can help. Can you please explain the issue and assign me?

**Comment by RainbowDashLabs** [comment]
@danger-ahead 
Hoped the issue was already clear :D If you have more precise questions feel free to ask.

**Comment by RainbowDashLabs** [comment]
Word boundaries enforce that these signs are ignored anyway. Therefore this is not required anymore.

See https://github.com/RainbowDashLabs/reputation-bot/commit/dd42d0eb79318033bc189778839800d42c75121c for more
