### ISSUE TITLE
Ephemeral for other users on rep promt

### ISSUE THREAD

**Issue by Taucher2003** [RainbowDashLabs/reputation-bot#55]
Related to the changes in #52

If another user clicks on the button, currently nothing happens.
That should send an ephemeral message for the user, so he knows, that he is ignored on the buttons

**Comment by DRSchlaubi** [comment]
isn't this even required because otherwise it will just say reaction failed

**Comment by Taucher2003** [comment]
> isn't this even required because otherwise it will just say reaction failed

This issue was requested by @RainbowDashLabs so he doesn't forget that

**Comment by RainbowDashLabs** [comment]
> isn't this even required because otherwise it will just say reaction failed

"Interaction failed" could be interpreted as an error on bot side by the user. I dont want that users assume the bot is broken in any way.
